### ISSUE TITLE
Are there any build instructions?

### ISSUE THREAD

**Issue by mikegioia** [fjsj/evee#1]
Hi - I was wondering if you had any instructions on building the app, specifically the client. The client JS files are all disparate but how are you building these together? Does Meteor do something behind the scenes? I'd appreciate any help!

**Comment by fjsj** [comment]
Hi Mike. Yes, Meteor just builds the project automatically. But FB API has changed considerably last time I saw, so I'm not sure the project will work anymore :(

Let me know if I can help you with something else.

**Comment by mikegioia** [comment]
Ahh thanks! I was just generally curious how it was being built but that answers my question. I'll have to look into Meteor.
